### ISSUE TITLE
Deploying the server

### ISSUE THREAD

**Issue by angelZambrano** [exherb/tornado-oauthlib#1]
Sorry I try to create a server that implements tornado-oauthlib, but I don't find an example about it.
this is my code:

import datetime
from flask import jsonify
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
import tornado
from tornado.web import RequestHandler
from model.models import OAuth2Client, OAuth2Grant, OAuth2BearerToken, User
from tornado_oauthlib.provider import OAuth2Provider

engine = create_engine('postgres://postgres:123456@localhost:5432/postgres', pool_size=10)
Session = sessionmaker(bind=engine)

oauth2 = OAuth2Provider()

@oauth2.clientgetter
def load_client(client_id):
    try:
        return  Session.query(OAuth2Client).where(OAuth2Client.client_id.val==client_id).first()
    except OAuth2Client.DoesNotExist:
        return None

@oauth2.grantgetter
def load_grant(client_id, code):
    try:
        return Session.query(OAuth2Grant).where(OAuth2Grant.client_id.val==client_id and OAuth2Grant.code.val==code).first()
    except OAuth2Grant.DoesNotExist:
        return None

@oauth2.grantsetter
def save_grant(client_id, code, request, *args, **kwargs):
    expires = datetime.utcnow() + datetime.timedelta(seconds=100)
    grant = OAuth2Grant(
        client=client_id,
        code=code['code'],
        redirect_uri=request.redirect_uri,
        _scopes=' '.join(request.scopes),
        user=request.handler.get_current_user(),
        expires=expires
    )

    Session.add(grant)
    return grant

@oauth2.tokengetter
def load_token(access_token=None, refresh_token=None):
    try:
        if access_token:
            #return OAuth2BearerToken.get(OAuth2BearerToken.access_token == access_token)
            return Session.query(OAuth2BearerToken).where(OAuth2BearerToken.access_token== access_token).first()
        elif refresh_token:
            #return OAuth2BearerToken.get(OAuth2BearerToken.refresh_token == refresh_token)
            return Session.query(OAuth2BearerToken).where(OAuth2BearerToken.refresh_token== refresh_token).first()
    except OAuth2BearerToken.DoesNotExist:
        return None

@oauth2.tokensetter
def save_token(token, request, *args, **kwargs):
    if request.response_type == 'token':
        user = request.handler.get_current_user()
    else:
        user = request.user
    #toks = OAuth2BearerToken.select()\
    #    .where(OAuth2BearerToken.client == request.client &
    #           OAuth2BearerToken.user == request.user)

    toks = Session.query(OAuth2BearerToken).where(OAuth2BearerToken.client== request.client & OAuth2BearerToken.user == request.user)
    # make sure that every client has only one token connected to a user
    for t in toks:
        t.delete_instance()

    expires_in = token.pop('expires_in')
    expires = datetime.utcnow() + datetime.timedelta(seconds=expires_in)

    tok = OAuth2BearerToken(
        access_token=token['access_token'],
        refresh_token=token.get('refresh_token', None),
        token_type=token['token_type'],
        _scopes=token['scope'],
        expires=expires,
        client=request.client,
        user=request.user,
    )

    Session.add(tok)
    return tok

@oauth2.usergetter
def get_user(username, password, *args, **kwargs):
    try:
        #user = User.get(User.username == username)
        user = Session.query(User).where(User.username == username).first()
    except User.DoesNotExist:
        return None
    if user.verify(password):
        return user
    return None

# '/oauth/authorize'
@oauth2.authorize_handler
class AuthorizeHandler(RequestHandler):

    def get(self, *args, **kwargs):
        client_id = kwargs.get('client_id')
        #client = Client.get(client_id=client_id)
        client = Session.query(OAuth2Client).where(OAuth2Client.client_id==client_id).first()
        kwargs['client'] = client
        self.render('oauthorize.html', **kwargs)

    def post(self):
        confirm = self.get_argument('confirm', 'no')
        return confirm == 'yes'

# '/oauth/token'
@oauth2.token_handler
class Tokenhandler(RequestHandler):

    def post(self):
        return {'version': '0.1.0'}

# '/oauth/revoke'
@oauth2.revoke_handler
class Revokehandler(RequestHandler):

    def post(self):
        pass

class UserHandler(RequestHandler):
    @oauth2.require_oauth('email')
    def get(self):
        user = self.oauth.user
        self.finish(jsonify(email=user.email, username=user.username))

def main():

    app = tornado.web.Application([
        (r'/oauth/authorize', AuthorizeHandler),
        (r'/oauth/token', Tokenhandler)
    ])
    app.listen(5001)
    print("Server Starting")
    tornado.ioloop.IOLoop.instance().start()

if __name__ == "__main__":
    main()

when I try to call http://localhost:5001/oauth/authorize with RESTFirefox I get this error:

 result = method(*self.path_args, **self.path_kwargs)
  File "/srv/samba/share/paty/tornado_server_with_oauth2/tornado_oauthlib/provider/oauth2.py", line 342, in get
    server = self.server
AttributeError: 'OAuth2Provider' object has no attribute 'server'

Please you cant help me?
Thanks in advance.

**Comment by exherb** [comment]
you need to call oauth2.init_app(application)
